### ISSUE TITLE
stuck at sending, refresh or scan for outputs don't do anything

### ISSUE THREAD

**Issue by aleqx** [GrinPlusPlus/GrinPlusPlus#115]
https://i.gyazo.com/6d0ae1b6287f88cfb9088a78a2b60795.png

This is on 0.7.5 windows 8.1 x64. The first row is not clickable. My other wallet running in Linux (official 3.0.0) doesn't see any locked transaction so nothing has been sent to the tx pool.

Clicking on refresh or scan (in options) doesn't do anything.

Any ideas?

**Comment by DavidBurkett** [comment]
Sending failed apparently. You'll have to cancel and try again

**Comment by aleqx** [comment]
I tried 5 times already. There ids a lot of these in ui.log (hundreds) after it failed the first time:

```
[2020-02-09 21:07:45.794] [error] Error: Object has been destroyed
    at C:\Users\SNIP\AppData\Local\Programs\GrinPlusPlus\resources\app.asar\app\background.js:1:13132
    at IncomingMessage.<anonymous> (C:\Users\SNIP\AppData\Local\Programs\GrinPlusPlus\resources\app.asar\app\background.js:1:3410)
    at IncomingMessage.emit (events.js:194:13)
    at endReadableNT (_stream_readable.js:1141:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

When it failed the first time it said:

```
[2020-02-09 20:13:59.377] [info] Sending to: https://poloniex.com/public?currency=GRIN&command=createDeposit&id=6b21bfcb-9b24-493a-858c-659e1ecc5c7a
[2020-02-09 20:13:59.378] [info] Calling (send) with data:
{"session_token":"u9+d7vROdphJ5BrPE5bPSlx7Yelv7KXRosyNX+vkD2FH/Sd51dsKhMyJJcE=","amount":200000000000,"fee_base":1000000,"selection_strategy":{"strategy":"SMALLEST","inputs":["0890eb624cf66d1d359c98c082f3e5fa16f410689c3bf590f383957dc1687486d8"]},"address":"https://poloniex.com/public?currency=GRIN&command=createDeposit&id=6b21bfcb-9b24-493a-858c-659e1ecc5c7a","post_tx":{"method":"STEM"}}
[2020-02-09 20:13:59.660] [info] Result: {"id":"b5f6b288-a3e0-4a37-b6ec-a940fc0c6898","jsonrpc":"2.0","result":{"slate":{"amount":"200000000000","fee":"8000000","height":"559498","id":"18ff121d-f57e-4cec-9199-7fc8300b7c0f","lock_height":"0","num_participants":2,"participant_data":[{"id":"0","message":null,"message_sig":null,"part_sig":null,"public_blind_excess":"039b2ed9dbdb2442c976c0042582b0da9c04e3558376d9287e8c96ca0b87a90391","public_nonce":"03c34c1b761b16343c35112bc8f559528b51d8fe2b3045b9f806ab068ca7a6f3b7"}],"tx":{"body":{"inputs":[{"commit":"0890eb624cf66d1d359c98c082f3e5fa16f410689c3bf590f383957dc1687486d8","features":"Plain"}],"kernels":[{"excess":"000000000000000000000000000000000000000000000000000000000000000000","excess_sig":"00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","features":"Plain","fee":"8000000","lock_height":"0"}],"outputs":[{"commit":"09c95809041ad5d0916df472e8f55641a1e4ed0da3862c4b967f2d760358b4f620","features":"Plain","proof":"eb42e2b1f78b5bb06a544ef13914046931492a6c181825ee8b3461ba78d7f2de5ca4f240b849891d0dc36aca2ce32d5d288a5ae2d7f5576ebbdaebee7fd6e7670cb403627469c55f481316dba17d4a1db5774738de9424f1200788951700cac904ea058a5e0e55d360528b373342d02f53618be548201af4afe15435bfa593863b9cfcc90326df4665b5eab8791cf5d14c1386db0f4ae644677c41bdd63d17acb39a149f298d003814d3f10a047bedf97d027abac4cd78024adab4e4acaf2270340ab35006f213b5f193276a9b8f9238da8e3d4f1031eec6387b35c4ccf113b8fbee00dbe654c776d2b3499f22545adce116fa5a131ae9670282c63482d7cbba8be80a807540044ff8d932f708380fca88d3477565873ce59e42e7f66e104c166699abc041789bcf0de7633ed7f06af9c2bd722f6f447cb60fc1f9f7d168236985c26165609b78e9066b71276f9071138742c7f827b8a353a3095b82ac3a4115c964032691c595261f27260f7a60a8d6c45353f9a56c45c67c05690595dad18861f5d150a7206c053d7cfcc194b9a5ea3776d490afe9430ee28285298cf09b28d75bd607cae3dd5a0981202d9263dafd1f9451f5479f4d465747defd0a50ee1bf41855531f7e564e1de843c501b4591008c6be3618016da72c944b97712204bcb6311c3b4be12b365a181e0cdf0d3c274368923885f6df46854ff8d578bcc622aea6e55ac73099dbae4e2d8426b7a5ffaaedc4a99b3ab930a382d2984a9f2cc20eb69b7ab3b31f444bfbc8348b261625f6d33cf5a496bdfd0d68a39a304c3871733439c4e1476c4b21caeab3fab55047b03674ec4aa9043cf90fea021115367b969ac8a88737e53fd23abe52c81427cc86d4120a1b4601f403fa043b2a9b26a885071bc4d2568a6991028d6016ee024b5f614be9702b23ba4b99355f3a158abc92f22f"}]},"offset":"11ed7ecb2df29b2d8bcf51e5b39056d1b7045f2e8e34b66d7dcd71a6126659a2"},"version_info":{"block_header_version":3,"orig_version":2,"version":2}},"status":"SENT"}}
[2020-02-09 20:14:00.315] [error] Receive_tx error: 
[2020-02-09 20:14:00.317] [error] Error: {"error":"Unable to deposit. "}
    at IncomingMessage.<anonymous> (C:\Users\SNIP\AppData\Local\Programs\GrinPlusPlus\resources\app.asar\node_modules\jayson\lib\client\http.js:76:23)
    at IncomingMessage.emit (events.js:199:15)
    at endReadableNT (_stream_readable.js:1141:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
[2020-02-09 20:14:00.318] [info] Receive Result: {"success":false,"error":{"code":400}}
[2020-02-09 20:14:00.318] [error] Receive failed with status: undefined
```

**Comment by DavidBurkett** [comment]
"Unable to deposit" is a Poloniex error. You'll have to contact their support

**Comment by aleqx** [comment]
Ok, but what about those hundreds of errors? Grin++ also now doesn't die when clicking the X button (i have to kill it forcefully from task manager)

**Comment by aleqx** [comment]
I wiped everything in my user profile and reinstalled, and upon launching it crashed, then said this: https://i.gyazo.com/dc11d3a7443d226ae88fdf3a02169489.png ... but I did completel wipe `.GrinPP`

**Comment by DavidBurkett** [comment]
Not sure. I don't have access to a windows 8.1 machine to test. It's not a problem on windows 10.

I'll see if I can find a trial version to test it out.

**Comment by DavidBurkett** [comment]
Is this still an issue in 1.0.2+? I've rewritten much of that logic for the 1.0.0 release, so I suspect it's fixed

**Comment by aleqx** [comment]
Haven't attempted any transactions in 1.x yet. I'll report if i meet issues so I'm closing this for now.
