### ISSUE TITLE
remote_endpoint: Transport endpoint is not connected

### ISSUE THREAD

**Issue by davidtavarez** [GrinPlusPlus/GrinPlusPlus#187]
```
terminate called after throwing an instance of 'std::system_error'
  what():  remote_endpoint: Transport endpoint is not connected

(gdb) bt -ful
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 68719476737, 140736372936896, 3, 0, 0, 8320808480468661363, 8030606865273283956, 140736372932722, 140736372939520, 140736372939528, 140736372939536, 140736372939768, 0,
            140736372939784, 0}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7cb1537 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x7ffff7e4b643 <_IO_2_1_stderr_+131>, sa_sigaction = 0x7ffff7e4b643 <_IO_2_1_stderr_+131>}, sa_mask = {__val = {140737352352928, 3432, 140737351039446,
              140737352352928, 1, 140737352349120, 140736372942592, 4294967295, 28, 93825010205280, 140737351046921, 10, 140737351048035, 10, 140737352349120, 140736372942592}}, sa_flags = -137328061,
          sa_restorer = 0x7fffe00ead08}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00005555554b840a in __gnu_cxx::__verbose_terminate_handler() [clone .cold.1] ()
No symbol table info available.
#3  0x0000555555b6de76 in __cxxabiv1::__terminate(void (*)()) ()
No symbol table info available.
#4  0x0000555555b6deb1 in std::terminate() ()
No symbol table info available.
#5  0x0000555555b6ca74 in __cxa_throw ()
No symbol table info available.
#6  0x000055555551437a in void asio::detail::throw_exception<std::system_error>(std::system_error const&) ()
No symbol table info available.
#7  0x00005555555865c4 in asio::detail::do_throw_error(std::error_code const&, char const*) [clone .isra.482] ()
No symbol table info available.
#8  0x000055555558b9b6 in asio::basic_socket<asio::ip::tcp>::remote_endpoint() const ()
No symbol table info available.
#9  0x0000555555587eb5 in Seeder::Accept(std::error_code const&) ()
No symbol table info available.
#10 0x000055555558b5c5 in asio::detail::reactive_socket_accept_op<asio::basic_socket<asio::ip::tcp>, asio::ip::tcp, std::_Bind<void (Seeder::*(Seeder*, std::_Placeholder<1>))(std::error_code const&)> >::do_complete(void*, asio::detail::scheduler_operation*, std::error_code const&, unsigned long) ()
No symbol table info available.
#11 0x0000555555587973 in Seeder::Thread_AsioContext(Seeder&) ()
No symbol table info available.
#12 0x0000555555b9cd4f in execute_native_thread_routine ()
No symbol table info available.
#13 0x00007ffff7fa6ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736372942592, -1066079769862116608, 140737488347806, 140737488347807, 140736372939776, 8396800, 1066223985347488512, 1066062199735806720},
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#14 0x00007ffff7d89def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by davidtavarez** [comment]
```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7cb1537 in __GI_abort () at abort.c:79
#2  0x00005555554b840a in __gnu_cxx::__verbose_terminate_handler() [clone .cold.1] ()
#3  0x0000555555b6de76 in __cxxabiv1::__terminate(void (*)()) ()
#4  0x0000555555b6deb1 in std::terminate() ()
#5  0x0000555555b6ca74 in __cxa_throw ()
#6  0x000055555551437a in void asio::detail::throw_exception<std::system_error>(std::system_error const&) ()
#7  0x00005555555865c4 in asio::detail::do_throw_error(std::error_code const&, char const*) [clone .isra.482] ()
#8  0x000055555558b9b6 in asio::basic_socket<asio::ip::tcp>::remote_endpoint() const ()
#9  0x0000555555587eb5 in Seeder::Accept(std::error_code const&) ()
#10 0x000055555558b5c5 in asio::detail::reactive_socket_accept_op<asio::basic_socket<asio::ip::tcp>, asio::ip::tcp, std::_Bind<void (Seeder::*(Seeder*, std::_Placeholder<1>))(std::error_code const&)> >::do_complete(void*, asio::detail::scheduler_operation*, std::error_code const&, unsigned long) ()
#11 0x0000555555587973 in Seeder::Thread_AsioContext(Seeder&) ()
#12 0x0000555555b9cd4f in execute_native_thread_routine ()
#13 0x00007ffff7fa6ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#14 0x00007ffff7d89def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
